### PR TITLE
Use paths=source_relative if the version is 2

### LINKED ISSUE #49: Use paths=source_relative flag
https://developers.google.com/protocol-buffers/docs/reference/go-generated documents a flag `paths=source_relative`:

> If the paths=source_relative flag is specified, the output file is placed in the same relative directory as the input file. For example, an input file protos/buzz.proto results in an output file at protos/buzz.pb.go.

This fixes a chief issue with module-based output, allowing to move to using `--go_out=.` to work from the repo root.

We should probably move the version 2 config to emit with these options.

### PR DESCRIPTION
**Pull request by kzys**
Fixes #49.

Signed-off-by: Kazuyoshi Kato <katokazu@amazon.com>

### CODE REVIEW

**Comment by dmcgowan** [comment]
Will this fix the protobuild outside go path issue?

**Comment by kzys** [comment]
It should be. Let me update GitHub Actions.

**Comment by kzys** [comment]
It seems working but I don't like the fact we need to modify Protobuild.toml (see 71a8126110dab5981779ebd4e2d4265856320622).

**Comment by dmcgowan** [comment]
That is a configuration we have defined. Should we try and keep the module name in there and can add it back for the txt files? I don't think small changes to protobuild file is a bit deal to make it work, as long as it works both ways after

**Comment by samuelkarp** [comment]
I also opened a PR that supports source_relative (https://github.com/containerd/protobuild/pull/55) before realizing that you had opened this already.  I'm happy to close mine if you'd prefer to have source_relative by default instead of optional.

**Pull request closed without merging**
