### PR TITLE
Run protobuild on GitHub Actions

### PR DESCRIPTION
**Pull request by kzys**
protobuild currently have no tests. Instead this change actually runs
protobuild on GitHub Actions to make sure we don't accidentally change
the result of the command.

### CODE REVIEW

**Comment by estesp** [comment]
`go.mod` needs the name update as well

**Review by estesp — APPROVED** [review]
LGTM

**Review by mikebrow — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by dmcgowan — APPROVED** [review]

**Pull request merged**
